/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        darkBlue: "#151542",
        lightWhite: "#f7f7f7",
        customGray: "#686868",
        "theme-color": "var(--theme-color)",
        "bg-blank": "var(--bg-blank)",
        "funnel-theme-color": "var(--funnel-theme-color)",
        "theme-alter-color": "var(--theme-alter-color)",
        "theme-filter-color": "var(--theme-filter-color)",
        "dark-theme-color": "var(--dark-theme-color)",
        "filter-border-color": "var(--filter-border-color)",
        "theme-search-color": "var(--theme-search-color)",
        "table-header-color": "var(--table-header-color)",
        "footer-theme-color": "var(--footer-theme-color)",
        "model-overlay-color": "var(--model-overlay-color)",
        "grayscale-0": "var(--grayscale-0)",
        "grayscale-100": "var(--grayscale-100)",
        "grayscale-20": "var(--grayscale-20)",
        "grayscale-200": "var(--grayscale-200)",
        "grayscale-2100": "var(--grayscale-2100)",
        "grayscale-2200": "var(--grayscale-2200)",
        "grayscale-2300": "var(--grayscale-2300)",
        "grayscale-2400": "var(--grayscale-2400)",
        "grayscale-2500": "var(--grayscale-2500)",
        "grayscale-2600": "var(--grayscale-2600)",
        "grayscale-2700": "var(--grayscale-2700)",
        "grayscale-2800": "var(--grayscale-2800)",
        "grayscale-2900": "var(--grayscale-2900)",
        "grayscale-300": "var(--grayscale-300)",
        "grayscale-400": "var(--grayscale-400)",
        "grayscale-500": "var(--grayscale-500)",
        "grayscale-600": "var(--grayscale-600)",
        "grayscale-700": "var(--grayscale-700)",
        "grayscale-800": "var(--grayscale-800)",
        "grayscale-900": "var(--grayscale-900)",
      },
    },
  },
  plugins: [],
};
